-- Add AI review fields to question_reviews table
-- These are populated by the scripts/review-questions.ts batch review script.
-- is_ai_review = TRUE means this record was auto-generated by the AI script;
-- human reviews overwrite it with is_ai_review = FALSE.

ALTER TABLE question_reviews
  ADD COLUMN IF NOT EXISTS ai_flags    TEXT[]  NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ai_notes    TEXT,
  ADD COLUMN IF NOT EXISTS is_ai_review BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN question_reviews.ai_flags     IS 'Flag codes set by the AI review script (wrong_answer, ui_mismatch, etc.)';
COMMENT ON COLUMN question_reviews.ai_notes     IS 'One-sentence AI explanation of the flags';
COMMENT ON COLUMN question_reviews.is_ai_review IS 'TRUE = auto-generated by AI script; FALSE = human reviewed';
